# Generated by Django 2.1.3 on 2018-11-16 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
